# socials
twitter = "@xsuz10074"
# largeTwitterCard = true # set to true if you want to show a large twitter card image. The default is a small twitter card image
introDescription = "Tokyo Tech 22B"
# description = "" # Set your site's meta tag (SEO) description here. Alternatively set this description in your home page content file e.g. content/_index.md. Whatever is set in the latter will take precedence.
# keywords = ["design", "clarity", "hugo theme"] # Set your site's meta tag (SEO) keywords here. Alternatively set these in your home page content file e.g. content/_index.md. Whatever is set in the latter will take precedence.

showShare = true # Uncomment to not show share buttons on each post. Also available in each post's front matter.

# directory(s) where your articles are located
mainSections = ["post"] # see config details here https://gohugo.io/functions/where/#mainsections

comments = false

dateFormat = "2006-01-02" # Default to "Jan 2, 2006".

since = 2022

[author]
name = "Yuta Suzuki"
photo = "img/avatar128x128.jpg" #include this if you would like to show the author photo on the sidebar