[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Archives"
  url = "archives/"
  weight = -109

[[main]]
  name = "Aerodynamics"
  url = "categories/aerodynamics/"
  weight = -107

[[main]]
  name = "Electronics"
  url = "categories/electronics/"
  weight = -106


# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/xsuz"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/xsuz10074"