[[main]]
  name = "home"
  url = ""
  weight = -110

[[main]]
  name = "archives"
  url = "archives/"
  weight = -109

[[main]]
  name = "about"
  url = "about/"
  weight = -108

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/xsuz"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/xsuz10074"